// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8P57Apf5RJlnL3ODCTCich3dF1RQ2yDk',
    appId: '1:757439910106:web:8273f0a1cd95aede0495e3',
    messagingSenderId: '757439910106',
    projectId: 'test-project-43a0c',
    authDomain: 'test-project-43a0c.firebaseapp.com',
    storageBucket: 'test-project-43a0c.firebasestorage.app',
    measurementId: 'G-8891K6WXPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2jyfzeXRdQeerSo-e4nlr9N6_nMGlgic',
    appId: '1:757439910106:android:c79818bdcfa0c6d10495e3',
    messagingSenderId: '757439910106',
    projectId: 'test-project-43a0c',
    storageBucket: 'test-project-43a0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtZkpVHCJMIuqniF55ATCojdIOFTmg8pw',
    appId: '1:757439910106:ios:1d199e5d564635de0495e3',
    messagingSenderId: '757439910106',
    projectId: 'test-project-43a0c',
    storageBucket: 'test-project-43a0c.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtZkpVHCJMIuqniF55ATCojdIOFTmg8pw',
    appId: '1:757439910106:ios:1d199e5d564635de0495e3',
    messagingSenderId: '757439910106',
    projectId: 'test-project-43a0c',
    storageBucket: 'test-project-43a0c.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8P57Apf5RJlnL3ODCTCich3dF1RQ2yDk',
    appId: '1:757439910106:web:70312d8bee5ec8220495e3',
    messagingSenderId: '757439910106',
    projectId: 'test-project-43a0c',
    authDomain: 'test-project-43a0c.firebaseapp.com',
    storageBucket: 'test-project-43a0c.firebasestorage.app',
    measurementId: 'G-53BWGB6J2E',
  );
}
